- hosts: masters
  become: false

  tasks:
    - name: Add Helm Repository for nfs-subdir-external-provisioner
      shell: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

    - name: Install nfs-subdir-external-provisioner
      shell: helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ nfs_server_ip }} --set nfs.path={{ nfs_server_path }} --set storageClass.onDelete=true

    - name: Apply kube-nfs-pvc
      shell: kubectl apply -f /vagrant/provisioning/manifests/kube-nfs-pvc.yaml

    - name: Add Helm Repository for prometheus
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    
    - name: Prepate MetalLB installation
      shell: "kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e \"s/strictARP: false/strictARP: true/\" | kubectl apply -f - -n kube-system"

    - name: Install MetalLB
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml

    # Despliegue Baremetal para probar que funciona 
    #- name: Install ingress controller
    #  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/baremetal/deploy.yaml
    - name: Install ingress-nginx controller
      shell:  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
    
    - name: Wait to avoid timeouts
      pause:
        seconds: 20

    - name: Configurate metallb
      shell: kubectl apply -f /vagrant/provisioning/manifests/kube-metallb.yaml
    
    - name: Wait to avoid timeouts
      pause:
        seconds: 20

    - name: Deploy kube-metrics
      shell: kubectl apply -f /vagrant/provisioning/manifests/kube-metrics.yaml

    - name: Wait to avoid timeouts
      pause:
        minutes: 1

    - name: Update helm repos
      shell: helm repo update

    - name: Install and deploy prometheus
      kubernetes.core.helm: # helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set=alertmanager.persistentVolume.existingClaim=nfs-pvc,server.persistentVolume.existingClaim=nfs-pvc,grafana.persistentVolume.existingClaim=nfs-pvc
        name: kube-prometheus-stack
        namespace: default
        chart_ref: prometheus-community/kube-prometheus-stack
        atomic: true
        set_values:
          - value: alertmanager.persistentVolume.existingClaim=nfs-pvc
          - value: server.persistentVolume.existingClaim=nfs-pvc
          - value: grafana.persistentVolume.existingClaim=nfs-pvc

    - name: Deploy ingress
      shell: kubectl apply -f /vagrant/provisioning/manifests/kube-ingress.yaml