- hosts: sec_masters
  become: yes

  tasks:
    - name: Enable keepalived
      systemd_service:
        name: keepalived
        enabled: true

    - name: Delete keepalive.conf
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent

    - name: Copy config file
      copy:
        src: /vagrant/provisioning/keepalived.conf
        dest: /etc/keepalived/
        remote_src: yes
    
    - name: Change keepalived state
      shell: sudo sed -i 's/state MASTER/state BACKUP/' /etc/keepalived/keepalived.conf

    - name: Change keepalived priority
      shell: sudo sed -i 's/priority 150/priority 100/' /etc/keepalived/keepalived.conf

    - name: Copy check_apiserver.sh
      copy:
        src: /vagrant/provisioning/check_apiserver.sh
        dest: /etc/keepalived/
        remote_src: yes

    - name: Enable haproxy
      systemd_service:
        name: haproxy
        enabled: true

    - name: Delete haproxy.cfg
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent

    - name: Copy haproxy.cfg
      copy:
        src: /vagrant/provisioning/haproxy.cfg
        dest: /etc/haproxy/
        remote_src: yes

    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted
      #shell: systemctl restart keepalived
    
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted
      #shell: systemctl restart haproxy

    - name: Join cluster as ControlPlane node
      shell: sh /vagrant/provisioning/control_plane_join_command.sh
    
    - name: Create .kube dir
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: 0755
    
    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0600