- hosts: sec_masters:workers
  become: yes

  tasks:
    - name: Update exportfs list
      shell: showmount --exports nfs-server

    - name: Mount NFS share
      shell: mount -t nfs -o nfsvers=4 nfs-server:/data/nfs /mnt

    - name: Make it persistent
      lineinfile:
        path: /etc/fstab
        line: nfs-server:/data/nfs  /mnt  nfs defaults  0 0