- hosts: masters
  become: yes

  tasks:
    - name: Create partition and filesystem
      community.general.parted:
        device: /dev/sdb
        label: gpt
    
    - name: Create primary partition
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        align: optimal
      ignore_errors: yes

    - name: Verify partition alignment
      shell: "parted -s -- /dev/sdb align-check optimal 1"
      register: parted_result

    - name: Print parted check
      debug:
        var: parted_result

    - name: Format partition to XFS
      filesystem:
        fstype: xfs
        dev: /dev/sdb1

    - name: Create data dir
      file:
        path: /data
        state: directory

    - name: Add /dev/sdb1 to fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/sdb1 /data xfs defaults 0 0"
    
    - name: Mount partition
      ansible.posix.mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        opts: defaults
        state: mounted

    - name: Create directory to export
      file:
        path: "{{ nfs_server_path }}"
        owner: nobody
        group: nobody
        mode: '2770'
        state: directory

    - name: Export directory
      lineinfile:
        path: /etc/exports
        line: "{{ nfs_server_path }}\t{{ nfs_server_net }}(rw,sync,no_subtree_check,no_root_squash)"

    - name: Exportfs
      shell: exportfs -av

    - name: Restart nfs-server
      service:
        name: nfs-server
        state: restarted
      #shell: systemctl restart nfs-server

    - name: Enable nfs-server
      service:
        name: nfs-server
        enabled: true

    - name: Enable rpcbind
      service:
        name: rpcbind
        enabled: true
      #shell: systemctl enable nfs-server rpcbind