- hosts: sec_masters
  become: yes

  tasks:
    - name: Enable keepalived
      shell: systemctl enable keepalived

    - name: Delete keepalive.conf
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent

    - name: Copy config file
      copy:
        src: /vagrant/provisioning/keepalived.conf
        dest: /etc/keepalived/
        remote_src: yes
    
    - name: Change keepalived state
      shell: sudo sed -i 's/state MASTER/state BACKUP/' /etc/keepalived/keepalived.conf

    - name: Change keepalived priority
      shell: sudo sed -i 's/priority 255/priority 254/' /etc/keepalived/keepalived.conf

    - name: Copy check_apiserver.sh
      copy:
        src: /vagrant/provisioning/check_apiserver.sh
        dest: /etc/keepalived/
        remote_src: yes

    - name: Enable haproxy
      shell: systemctl enable haproxy

    - name: Delete haproxy.cfg
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent

    - name: Copy haproxy.cfg
      copy:
        src: /vagrant/provisioning/haproxy.cfg
        dest: /etc/haproxy/
        remote_src: yes

    - name: Restart keepalived
      shell: systemctl restart keepalived
    
    - name: Restart haproxy
      shell: systemctl restart haproxy


    - name: Join cluster as ControlPlane node
      shell: sh /vagrant/provisioning/control_plane_join_command.sh
      register: join_or_not

    - name: Print join command
      debug:
        var: join_or_not
    
    - name: Create .kube dir
      file:
        path: /home/vagrant/.kube
        state: directory
        mode: 0755
    
    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0600